id: de.gematik.fhir.epa.medication.poc
canonical: https://gematik.de/fhir/epa-medication
name: ePA-Medication
status: draft
version: 3.0.0
fhirVersion: 4.0.1
publisher:
  name: gematik GmbH
  url: https://www.gematik.de
dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.3.2
  de.gematik.erezept-workflow.r4: 1.2.2
FSHOnly: true